modifications to dockerignore and dockerfile to get the image working

diff --git a/src/Dockerfile b/src/Dockerfile
--- a/src/Dockerfile
+++ b/src/Dockerfile
@@ -17,7 +17,6 @@ RUN \
   else echo "Lockfile not found." && exit 1; \
   fi
 
-
 # Rebuild the source code only when needed
 FROM base AS builder
 WORKDIR /app
@@ -30,13 +29,13 @@ COPY . .
 # ENV NEXT_TELEMETRY_DISABLED=1
 
 RUN \
-  if [ -f yarn.lock ]; then yarn run build; \
-  elif [ -f package-lock.json ]; then npm run build; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
-  
-RUN ls
+if [ -f yarn.lock ]; then yarn run build; \
+elif [ -f package-lock.json ]; then npm run build; \
+elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+else echo "Lockfile not found." && exit 1; \
+fi
+
+# RUN ls -R .next | head -50
 
 # Production image, copy all the files and run next
 FROM base AS runner
@@ -54,10 +53,7 @@ COPY --from=builder /app/public ./public
 # Automatically leverage output traces to reduce image size
 # https://nextjs.org/docs/advanced-features/output-file-tracing
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
-COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/
-
-RUN ls
-
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static/
 COPY --from=builder --chown=nextjs:nodejs /app/data ./data
 
 USER nextjs
